name: Verify Build

on:
  push:
    branches: [ master, citest ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  generate_versions:
    name: Generate versions
    runs-on: ubuntu-latest
    env:
      GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GE_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: generateTestTasksJson
      - id: setup-matrix
        run: echo "::set-output name=matrix::$(cat build/build-resources/androidTestTasks.json)"
      - name: debug
        run: echo ${{ steps.setup-matrix.outputs.matrix }}
    outputs:
      matrix: ${{ steps.setup-matrix.outputs.matrix }}

  sanity_check:
    name: Sanity check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: sanityCheck

  android_version_tests:
    name: Android version tests
    needs: [ generate_versions, sanity_check ]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        androidTestTask: ${{ fromJson(needs.generate_versions.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v2
      # Patch issue in platform-tools 31.0.3 where platform-tools/api/api-versions.xml is missing (see https://issuetracker.google.com/issues/195445762)
      - name: Patch api-versions
        run: sudo test -f $ANDROID_HOME/platform-tools/api/api-versions.xml || (sudo mkdir $ANDROID_HOME/platform-tools/api && sudo cp .github/api-versions.xml $ANDROID_HOME/platform-tools/api/api-versions.xml)
      - name: List Android Packages
        run: sudo $ANDROID_HOME/tools/bin/sdkmanager --list | sed -n '/Available Packages/q;p'
      - uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: ${{ matrix.androidTestTask }} -x signArchives
