name: Submit Dependency Graph
on:
  workflow_dispatch:
  push:
    branches:
      - main
  
permissions: write-all

jobs:
  sanity-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
    - name: Setup Gradle
      uses: gradle/gradle-build-action@dependency-graph
      with:
        dependency-graph: generate-and-submit
    - name: Run sanityCheck to generate dependency graph
      run: ./gradlew sanityCheck -Porg.gradle.java.installations.auto-download=false
      env:
        GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GE_SOLUTIONS_ACCESS_TOKEN }}
